import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cachier Client</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Cachier
        </h1>

        <p className={styles.description}>
          Get started by choosing a package depending on your language
        </p>

        <div className={styles.grid}>
          <a href="https://pypi.org/project/cachier-python" className={styles.card}>
            <h2>Python &rarr;</h2>
            <p>Use the python package on the pypi repository.</p>
          </a>

          <a href="www.npmjs.com/package/cachier-js" className={styles.card}>
            <h2>JavaScript &rarr;</h2>
            <p>Use the npm package on the npmjs repository.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example projects built on cachier.</p>
          </a>

          <a
            href="https://github.com/apinanyogaratnam/cachier-service/pkgs/container/cachier-service"
            className={styles.card}
          >
            <h2>Simple and timeless &rarr;</h2>
            <p>
              Instantly setup a cachier service using docker
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
